### PR TITLE
Adding logic to dump NDT results to CSV

### PR DESCRIPTION
**Pull request by mtlynch**
Adding a module that can take NDT test result objects and convert them into
a single CSV file that describes all of them.

The unit tests are a bit light because long term this is intended to be a
debugging utility and not part of the normal testmaster workflow. And also
because creating NdtResult instances by hand is _terrible_, but more unit
tests can be added if needed.

---

This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt-e2e-testmaster/3)

### CODE REVIEW

**Comment by pboothe** [comment]
Looks good. Two small comments, but nothing that needs review after you fix it.

<details><summary>

<i>Previously, mtlynch (Michael Lynch) wrote…</i></summary>



> #### Adding logic to dump NDT results to CSV
> 
> Adding a module that can take NDT test result objects and convert them into
> 
> a single CSV file that describes all of them.
> 
> The unit tests are a bit light because long term this is intended to be a
> 
> debugging utility and not part of the normal testmaster workflow. And also
> 
> because creating NdtResult instances by hand is _terrible_, but more unit
> 
> tests can be added if needed.
> 
> </details>

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-testmaster/3#-:-KIieG06JHt0GvGOSjDi:-742318176)_

**Comment by pboothe** [comment]
:lgtm:

<details><summary>

<i>Previously, pboothe (Peter Boothe) wrote…</i></summary>



> Looks good. Two small comments, but nothing that needs review after you fix it.
> </details>

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-testmaster/3#-:-KIieMIpui3HRqD2imWl:1417088721)_

**Comment by pboothe** [comment]
_[build, line 1 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-testmaster/3#-KIicAHOoxcr8qsFReEU:-KIicAHOoxcr8qsFReEV:1827264946) ([raw file](https://github.com/m-lab/ndt-e2e-testmaster/blob/3010ef3489e68435d7e0fd2704c5947cd642bedb/build#L1)):_

> ```
> #!/bin/bash
> ```

This `&&` stuff is unnecessary and bad practice. Instead, use the `-e` argument to bash.

Or, even better, make 

``` bash
set -e
```

be the first line of code after the `#!` line. That way you will be robust to people running it as `bash build` as well as `./build`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-testmaster/3)_

**Comment by pboothe** [comment]
_[testmaster/csv_convert.py, line 75 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-testmaster/3#-KIiclOanW-no91zyPzg:-KIiclOb1ml_vwmhLt3S:90078463) ([raw file](https://github.com/m-lab/ndt-e2e-testmaster/blob/3010ef3489e68435d7e0fd2704c5947cd642bedb/testmaster/csv_convert.py#L75)):_

> ``` Python
> def _format_float(value):
>     if value is None:
>         return None
> ```

please `return ''`, that way the function is well-typed

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-testmaster/3)_

**Comment by mtlynch** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

_[build, line 1 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-testmaster/3#-KIicAHOoxcr8qsFReEU:-KIifyz_p_flPznpSoPP:1941690963) ([raw file](https://github.com/m-lab/ndt-e2e-testmaster/blob/3010ef3489e68435d7e0fd2704c5947cd642bedb/build#L1)):_
<details><summary>

<i>Previously, pboothe (Peter Boothe) wrote…</i></summary>



> This `&&` stuff is unnecessary and bad practice. Instead, use the `-e` argument to bash.
> 
> Or, even better, make 
> 
> ``` bash
> set -e
> ```
> 
> be the first line of code after the `#!` line. That way you will be robust to people running it as `bash build` as well as `./build`
> </details>
> Ah, good tip. Way cleaner.

---

_[testmaster/csv_convert.py, line 75 [r1]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-testmaster/3#-KIiclOanW-no91zyPzg:-KIig1bizAXaM3245orB:-499146009) ([raw file](https://github.com/m-lab/ndt-e2e-testmaster/blob/3010ef3489e68435d7e0fd2704c5947cd642bedb/testmaster/csv_convert.py#L75)):_
<details><summary>

<i>Previously, pboothe (Peter Boothe) wrote…</i></summary>



> please `return ''`, that way the function is well-typed
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-testmaster/3)_

**Pull request merged**
